dist: xenial    # required for Python >=3.7; see https://docs.travis-ci.com/user/languages/python/#specifying-python-versions
language: python
python: 3.7
install:
  - pip install -r pipenv.txt
script:
  - pipenv install --dev
# we do want black + flake8, but we need to get results first
# - pipenv run flake8
  
